training:
  checkpoint_dir: "checkpoints/mbconv_333_try1"  # Directory to save model checkpoints
  batch_size: 64  # Number of samples per training batch
  epochs: 200  # Total number of training epochs
  steps_per_epoch: 700  # Number of batches to process before an epoch is considered finished
  initial_lr: 0.1  # Starting learning rate for the optimizer
  min_lr: 0.001  # Minimum learning rate for scheduling
  momentum: 0.9  # Momentum factor for the SGD optimizer
  weight_decay: 0.0001  # L2 regularization factor for weights

model:
  stem_conv_filters: 16  # Number of filters for the initial (stem) convolution layer
  stem_conv_stride: 1  # Stride applied to the initial (stem) convolution layer
  block_type: "resnet_basic"  # Options: "resnet_basic", "preact_resnet",
    # "resnet_bottleneck", "inverted_residual", "mbconv", "convnext"
  repeats: [3, 3, 3]  # Number of times the block is repeated in each stage
  filters: [16, 32, 64]  # Number of filters (channels) for each stage
  kernels: [3, 3, 3]  # Kernel size for convolutions in each stage
  strides: [1, 2, 2]  # Stride applied to the first block of each stage
  expansions: [1, 6, 6]  # expansions applied to mbconv
  activation: "default"  # Options: "default", "relu", "relu6", "swish", "silu", "gelu"
  kernel_initializer: "he_uniform"  # Options: "he_normal", "he_uniform", "glorot_uniform"
  top_conv_filters: 128  # Number of filters for the final convolution layer before classification
  classifier_dropout_rate: 0.5  # Dropout rate applied to the dense classification head


augmentation:
  flip_prob: 0.5  # Probability of horizontal flip
  brightness_prob: 0.5  # Probability to apply random brightness
  brightness_delta: 0.2  # Max delta for brightness adjustment
  contrast_prob: 0.5  # Probability to apply random contrast
  contrast_lower: 0.66  # Lower bound for contrast factor
  contrast_upper: 1.5  # Upper bound for contrast factor
  saturation_prob: 0.5  # Probability to apply random saturation
  saturation_lower: 0.66  # Lower bound for saturation factor
  saturation_upper: 1.5  # Upper bound for saturation factor
  hue_prob: 0.5  # Probability to apply random hue
  hue_delta: 0.1  # Max delta for hue adjustment
  target_size: [32, 32]  # Target output resolution
  pad_crop_style: "cifar10"  # Options: "imagenet", "cifar10"
  pad_crop_prob: 0.9  # Probability to apply random padding
  pad_max_range: 0.25  # Range for dynamic ratio padding
  crop_min_range: 0.75  # Range for crop area relative to original
  aspect_ratio_range: [0.66, 1.5]  # Range for crop aspect ratio
  resize_method: "bilinear"  # Options: "bilinear", "bicubic"
  cutout_prob: 0.5  # Probability to apply cutout
  cutout_min_size: 4  # Minimum size of the cutout square
  cutout_max_size: 8  # Maximum size of the cutout square
  normalization: "minus1_1"  # Options: "0_1", "minus1_1", "cifar10"
